In [1]:
import numpy as np

dane są parametry statystyczne dwóch klas:

$\mu_A = \begin{bmatrix} 0 \\-1 \\-8 \end{bmatrix} 
\mu_B = \begin{bmatrix} 5 \\ 1 \\-1 \end{bmatrix}$

$C_A = \begin{bmatrix} 1&1&0\\1&2&-1\\0&-1&4 \end{bmatrix}$
$C_B = \begin{bmatrix} 2&0&0\\0&1&1\\0&1&2 \end{bmatrix}$

Która jednowymiarowa przestrzeń cech będzie najlepsza z punktu widzenia możliwości 
przeprowadzenia liniowej separacji próbek tych klas?


In [2]:
uA = np.array([[0],[-1],[-8]])
uB = np.array([[5],[1],[-1]])
cA = np.array([[1,1,0],[1,2,-1],[0,-1,4]])
cB = np.array([[2,0,0],[0,1,1],[0,1,2]])

$$F = \frac{|\mu^A - \mu^B|}{\sigma^A +\sigma^B}$$

In [3]:
# F1
np.abs(uA[0] - uB[0]) /  (np.sqrt(cA[0,0]) + np.sqrt(cB[0,0]))

array([2.07106781])

In [4]:
# F2
np.abs(uA[1] - uB[1]) /  (np.sqrt(cA[1,1]) + np.sqrt(cB[1,1]))

array([0.82842712])

In [5]:
# F3
np.abs(uA[2] - uB[2]) /  (np.sqrt(cA[2,2]) + np.sqrt(cB[2,2]))

array([2.05025253])

najlepszą cechą będzie cecha 1(najwyższy współczynnik)

Jak wyznaczyć najlepszą przestrzeń dwuwymiarową?
W celu wyznaczenia najlepszej przestrzeni dwuwymiarowej należy wyznaczyć wartość 
współczynnika Fishera dla każdej możliwej kombinacji par współczynników.

$$F_{12} = \frac{\sqrt{(\mu_{A1}-\mu_{B1})^2+(\mu_{A2}-\mu_{B2})^2}} {\sigma_{A22}+\sigma_{A33}+\sigma_{B22}+\sigma_{B33}}$$

In [6]:
# F12
np.sqrt((uA[0] - uB[0])**2 + (uA[1] - uB[1])**2) /((cA[0,0]) + (cA[1,1]) + (cB[0,0] + (cB[1,1])))

array([0.89752747])

In [7]:
# F13
np.sqrt((uA[0] - uB[0])**2 + (uA[2] - uB[2])**2) /((cA[0,0]) + (cA[2,2]) + (cB[0,0] + (cB[2,2])))

array([0.95581392])

In [8]:
# F23
np.sqrt((uA[1] - uB[1])**2 + (uA[2] - uB[2])**2) /((cA[1,1]) + (cA[2,2]) + (cB[1,1] + (cB[2,2])))

array([0.8089011])

najlepszą parą cech będzie para 1,3(najwyższy współczynnik)