In [1]:
import numpy as np

Dane są próbki dwóch klas A i B. Pierwsza klasa składa się z czterech próbkę:
$x_1^a=\begin{bmatrix}1\\1\end{bmatrix}
x_2^a=\begin{bmatrix}2\\2\end{bmatrix}
x_3^a=\begin{bmatrix}0\\3\end{bmatrix}
x_4^a=\begin{bmatrix}3\\0\end{bmatrix}$

O klasie B wiadomo, że wektor średni próbek tej klasy i jej macierz kowariancji to:
$C^b=\begin{bmatrix} c_6 &1\\ 1 &1 \end{bmatrix}
\mu^b=\begin{bmatrix}c_5\\c_4\end{bmatrix}$

gdzie $c_4c_5c_6$ to trzy ostatnie cyfry indeksu

określić wynik klasyfikacji dla próbki $X=\begin{bmatrix}0 \\ 0 \end{bmatrix}$

In [2]:
xA = np.array([[1,2,0,3],[1,2,3,0]])
cB = np.array([[3,1],[1,1]])
uB = np.array([[-2],[-2]])
X = np.array([[0],[0]])


$$\mu^A =\frac{1}{4}\begin{bmatrix} 1+2+0+3 \\ 1+2+0+3 \end{bmatrix}$$

In [3]:
uA = (1/4) * xA.sum(axis=1)
uA

array([1.5, 1.5])

#### Macierz odchylenia(pomocnicza)
$$(x^A - \mu^A) = (\begin{bmatrix} 1&2&0&3\\1&2&0&3 \end{bmatrix} \begin{bmatrix}1.5&1.5&1.5&1.5 \\1.5&1.5&1.5&1.5\end{bmatrix})$$

In [4]:
xm =  np.subtract(xA, uA.reshape(2,1))
xm

array([[-0.5,  0.5, -1.5,  1.5],
       [-0.5,  0.5,  1.5, -1.5]])

#### Macierz kowariancji
$$ C^a= \frac{1}{4} * (x^A - \mu^A) *(x^A - \mu^A)^T $$

In [5]:
cA = (1/4)*xm@xm.T
cA

array([[ 1.25, -1.  ],
       [-1.  ,  1.25]])

#### Selekcja cech - kryterium fishera

$$F = \frac{|\mu^A - \mu^B|}{\sigma^A +\sigma^B}$$


In [6]:
# F1
np.abs(uA[0] - uB[0]) /  (np.sqrt(cA[0,0]) + np.sqrt(cB[0,0]))

array([1.22803364])

In [7]:
# F2
np.abs(uA[1] - uB[1]) /  (np.sqrt(cA[1,1]) + np.sqrt(cB[1,1]))

array([1.65247584])

Z punktu widzenia możliwość poprawnej klasyfikacji próbek lepszą cechą jest cecha 2 ponieważ F2> F1 

obliczamy odległość punktu od klasy na podstawie cechy 2

$$d(x, (\mu_2^A\sigma_2^A)) = \frac{|x-\mu_2^A|}{\sigma_2^A}$$

In [8]:
# X[1] bo lepsza była 2 cecha
# klasa A
np.abs(X[1] - uA[1]) / np.sqrt(cA[1,1])

array([1.34164079])

In [9]:
# klasa B
np.abs(X[1] - uB[1]) / np.sqrt(cB[1,1])

array([2.])

Z wyliczonych odległości wynika że punkt x należy do klasy A

off topic
dla cechy 1 wyniki są odwrotne, punkt X zostałby przypisany do klasy B:

In [10]:
np.abs(X[0] - uA[0]) / np.sqrt(cA[0,0])

array([1.34164079])

In [11]:
np.abs(X[0] - uB[0]) / np.sqrt(cB[0,0])

array([1.15470054])